services:
  mailcatcher:
    image: sj26/mailcatcher
    restart: unless-stopped
    environment:
      HOST_WEB_PORT: ${HOST_WEB_PORT:-80}
      HOST_SMTP_PORT: ${HOST_SMTP_PORT:-1025}
    ports:
      - target: 1080
        published: ${HOST_WEB_PORT:-80}
        protocol: tcp
      - target: 1025
        published: ${HOST_SMTP_PORT:-1025}
        protocol: tcp
